d8-contrib-modules/key

readme.md

This is really just a test of Travis CI integration on pull request. I think i accidentally cancelled something.

Add the travis-ci build status to the readme file.

---

src/KeyManager.php
tests/src/KeyManagerTest.php

Per Pull Request #10.
Is there a different method that should be called, and what should the expected output be?

Fix KeyManager::getDefaultKeyContent() method

---

config/schema/key.schema.yml
key.services.yml
readme.md
src/Annotation/KeyType.php
src/KeyManager.php
src/Plugin/KeyType/FileKey.php
src/Plugin/KeyType/SimpleKey.php
src/Tests/KeyService.php
tests/assets/testkey.txt
tests/src/KeyManagerTest.php

1. Adds annotation for storage method
2. Extends service for storage method and key type filters
3. Adds simple tests for both service functions added
4. Bug fixes schema for file type

Storage method

---

key.info.yml
key.links.menu.yml
src/Entity/Key.php
tests/src/KeyManagerTest.php
tests/src/KeyTestBase.php

Fixed a few typos, capitalized the module's name, and added better module and menu descriptions.

Miscellaneous code cleanup.

---

readme.md

The readme file has been updated to provider better descriptions of how to manage keys, how to create new key providers, and how to use keys within other modules.

Updated documentation.

---

key.routing.yml
src/Entity/Key.php

Make route paths for key management conform to Drupal standard

---

key.links.menu.yml
key.routing.yml
src/Entity/Key.php
src/Tests/KeyService.php

1. Adds admin/config/security
2. Sets parent of main config form to admin/config/security
3. Removes parent of admin/structure

Fixing paths and adding security path

---

phpunit.xml
src/Entity/Key.php
tests/src/Entity/KeyEntityTest.php

Finish off coverage for Entity class.
A couple of tweaks to files:
1. Ignore the Simpletests directory when calculating coverage. :-)
2. Fix code standard typo.

Key entity coverage

---

src/Tests/KeyListBuilder.php

Provide a better message when no keys are available.

---

src/Form/KeyForm.php

I missed this when changing "key type" to "key provider".

Changed class name for AJAX wrapper.

---

config/schema/key.schema.yml
src/Entity/Key.php
src/Form/KeyForm.php
src/Tests/KeyService.php

Added Description field for keys.

---

src/Entity/Key.php
src/KeyRepository.php

I fixed the full docblocks to be in line with the documentation standards.

Issue 49: fixed several docblocks

---

src/Controller/KeyListBuilder.php

More info about EntityListBuilder::getLabel deprecation: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21EntityListBuilder.php/function/EntityListBuilder%3A%3AgetLabel/8

Update key list table

---

src/Form/KeyDefaultForm.php

Fixed confirmation messages when setting or unsetting default key.

---

src/KeyRepository.php

Fixed error when setting a default key when the default is already set.

---

src/Form/KeyDefaultForm.php

Changed confirmation text and button text when unsetting default key

---

src/Entity/Key.php
src/Form/KeyForm.php
src/KeyProviderInterface.php
src/Plugin/KeyProvider/ConfigKeyProvider.php
src/Plugin/KeyProvider/FileKeyProvider.php

Modifies the key configuration form to allow key providers access to all form fields and updates each of the provided providers to accept the new interface.

Implements #72.

---

key.links.menu.yml
key.routing.yml
readme.md
src/Entity/Key.php
src/Tests/KeyListBuilder.php
src/Tests/KeyService.php

Issue #70.
This PR is in case we can't figure out a way to define the Security section that works for multiple modules.

Moved from Security to System in Configuration hierarchy.

---

src/KeyRepository.php

Load an array of key names, useful as options in form fields.

---

config/schema/key.schema.yml
src/Entity/Key.php
src/Form/KeyForm.php
src/KeyInterface.php
src/Plugin/KeyProvider/ConfigKeyProvider.php
src/Plugin/KeyProvider/FileKeyProvider.php
src/Tests/KeyListBuilder.php
src/Tests/KeyService.php
tests/src/Entity/KeyEntityTest.php
tests/src/KeyRepositoryTest.php

Changed "Key Settings" to "Key Provider Settings" globally.
